# Generated by Django 3.2.9 on 2021-11-25 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=200)),
                ('subject', models.CharField(max_length=80)),
                ('message', models.TextField(max_length=4000)),
            ],
        ),
    ]
