# Generated by Django 3.2.9 on 2021-11-23 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='view',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='view',
            name='home',
        ),
        migrations.AddField(
            model_name='view',
            name='country',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='view',
            name='custom_title',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
