# Generated by Django 3.2.9 on 2021-11-23 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_auto_20211123_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='view',
            name='city',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='view',
            name='state',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
