# Generated by Django 3.2.9 on 2021-11-18 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_auto_20211118_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='view',
            name='home',
            field=models.BooleanField(default=False),
        ),
    ]
