# Generated by Django 3.2.9 on 2021-11-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(default='tag', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='tags',
            field=models.CharField(default='e', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='description',
            field=models.CharField(default='ads', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='tags',
            field=models.CharField(default='aasd', max_length=250),
            preserve_default=False,
        ),
    ]
