# Generated by Django 3.2.9 on 2021-11-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211110_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='version',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
