# Generated by Django 3.2.9 on 2021-11-11 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_topic_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='tags',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
