# Generated by Django 3.2.9 on 2021-11-12 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_topic_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='display_name',
            field=models.CharField(default='name', max_length=100),
            preserve_default=False,
        ),
    ]
