# Generated by Django 3.2.9 on 2021-11-12 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_category_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='not_useful',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topic',
            name='useful',
            field=models.IntegerField(default=0),
        ),
    ]
