# Generated by Django 3.2.9 on 2021-11-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20211112_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='output',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
