# Generated by Django 3.2.9 on 2021-11-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_topic_output'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='output',
            field=models.TextField(blank=True),
        ),
    ]
