# Generated by Django 3.2.9 on 2021-11-22 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_topic_output'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='not_useful',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='useful',
        ),
        migrations.AddField(
            model_name='topic',
            name='read_more',
            field=models.TextField(blank=True),
        ),
    ]
